services:
  - type: web
    name: bhumika-portfolio
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        fromDatabase:
          name: bhumika-portfolio-db
          property: connectionString

databases:
  - name: bhumika-portfolio-db
    databaseName: portfolio
    user: portfolio_user
    plan: free
